### PR TITLE
codegen: carry decl and func with containerinfo

### LINKED ISSUE #81: Specifying the same treebuilder config but different code in the `.toml` causes unexpected behaviour
The container `.toml` should carry all but the treebuilder logic for a type. However, due to implementation details, there is currently only one code provided per enum that treebuilder expects. This means that although the container `.toml` can have different code bodies but the same treebuilder, only one of the codes is used. Fix this by carrying the `ContainerInfo` around, perhaps in a shared pointer, rather than using the string map.

### PR DESCRIPTION
**Pull request by JakeHillion**
## Summary

Code generation of container function declarations and definitions currently runs through two maps, `typeToDeclMap` and `typeToFuncMap`. These are indexed by the `ContainerTypeEnum` which comes from a field in `ContainerInfo`. Rather than having this indirection, we should get the `decl` and `func` directly from the `ContainerInfo` object.

- Delete the `ContainerInfo` copy constructor as it now contains potentially very large strings.
- Change all copies of `ContainerInfo` to a reference to `OICodegen`'s `containerInfoList`.
- Remove `ContainerInfo` from `Serialize.h` as we no longer need to serialize it - only the numeric enum passes between `OICodeGen` and `TreeBuilder`, which makes sense!

Specifically, instead of looking up `typeToDeclMap[cinfo.ctype]` we now use `cInfo.codegen.decl` directly. The `.toml` files and code flow haven't really changed, except to avoid copying the types which are now quite big.

Closes #81

## Test plan

- CI
- `make test-devel`

Removed the serialization of `ContainerInfo` from CPP on `main`. Compilation fails with a tonne of static asserts, so I'm confident this is safe.

### CODE REVIEW

File: src/ContainerInfo.h [hunk 1]
```diff
@@ -73,6 +74,33 @@ ContainerTypeEnum containerTypeEnumFromStr(std::string& str);
 const char* containerTypeEnumToStr(ContainerTypeEnum ty);
 
 struct ContainerInfo {
+  struct Codegen {
+    std::string decl;
+    std::string func;
+  };
+
+  ContainerInfo(const ContainerInfo&) = delete;
```
Comment (ajor) [inline src/ContainerInfo.h:82]: Also delete the copy assignment constructor?

https://en.cppreference.com/w/cpp/language/rule_of_three

File: src/OICodeGen.h [hunk 2]
```diff
@@ -114,8 +114,11 @@ class OICodeGen {
   Config config{};
   FuncGen funcGen;
 
-  using ContainerTypeMap =
-      std::pair<ContainerInfo, std::vector<drgn_qualified_type>>;
+  using RefSharedContainerInfo =
```
Comment (ajor) [inline src/OICodeGen.h:117]: What does a reference_wrapper of a shared_ptr provide? Just an optimisation to avoid bumping the refcount?

**Review by ajor — COMMENTED** [review]
shared_ptrs seem unnecessary for us here and the lifetimes of the objects could be made more understandable by changing who owns them.

If these objects are needed by both OICodeGen and TreeBuilder, maybe they should be owned at the level that controls these two pieces (OIDebugger)?

File: src/ContainerInfo.h (hunk 1 above)
Comment (JakeHillion) [reply src/ContainerInfo.h:82]: Always useful having someone who knows what they're doing review C++ :)

I'm a little confused now though as I'm almost certain I don't need a custom destructor, I just want to avoid accidental expensive copies. Is this me misreading "requires" from the docs?

File: src/OICodeGen.h (hunk 2 above)
Comment (JakeHillion) [reply src/OICodeGen.h:117]: Yep. I was aiming for `&` for just reading, `&shared_ptr` for reading and potentially copying, and `shared_ptr` for owning. In theory this is quicker in a multithreaded context but as we're currently single threaded it's not, so it was a bit of future proofing. In hindsight it was most of the work of this diff to make the really awkward reference-wrappers work...

File: src/ContainerInfo.h (hunk 1 above)
Comment (JakeHillion) [reply src/ContainerInfo.h:82]: Oh, I think this bit explains it:

> Classes that manage non-copyable resources through copyable handles may have to declare copy assignment and copy constructor private and not provide their definitions or define them as deleted. This is another application of the rule of three: deleting one and leaving the other to be implicitly-defined will most likely result in errors.

**Comment by JakeHillion** [comment]
> shared_ptrs seem unnecessary for us here and the lifetimes of the objects could be made more understandable by changing who owns them.
> 
> If these objects are needed by both OICodeGen and TreeBuilder, maybe they should be owned at the level that controls these two pieces (OIDebugger)?

Well now I'm annoyed. It turns out the only thing we do with `ContainerInfo` in `TreeBuilder` is `kind = containerInfo->ctype;`, so it doesn't even need to see the object let alone own it.

I'm thinking of changing everything to `&` using `std::reference_wrapper`, which should be easy.

File: src/Common.h [hunk 3]
```diff
@@ -15,6 +15,7 @@
  */
 #pragma once
 #include <map>
+#include <memory>
```
Comment (ajor) [inline src/Common.h:18]:
```suggestion
```
Don't think this is needed in the latest version of this PR

File: src/ContainerInfo.cpp [hunk 4]
```diff
@@ -20,6 +20,8 @@
 
 #include <map>
 
+namespace fs = std::filesystem;
```
Comment (ajor) [inline src/ContainerInfo.cpp:23]:
```suggestion
```

**Review by ajor — APPROVED** [review]
