### PR TITLE
Cycles

### LINKED ISSUE #104: Cycle detection broken in OIL
Our pointer cycle detection currently relies on both JIT code and TreeBuilder to fully stop processing cycles.

This works in OID, but means that OIL ends up processing some nodes in a cycle (just the first?) more than once as it lacks the TreeBuilder component.

This seems like it should be able to work fully for both OID and OIL without the TreeBuilder component.

See test/integration/cycles.toml for tests which fail under OIL.

### Code References
Core JIT cycle detection code: https://github.com/facebookexperimental/object-introspection/blob/c4194a9fbc92f7ed0f14aec2d81e26b8f0c411fb/src/OITraceCode.cpp#L35-L74
Unique pointer cycle detection, making use of the above: https://github.com/facebookexperimental/object-introspection/blob/c4194a9fbc92f7ed0f14aec2d81e26b8f0c411fb/types/uniq_ptr_type.toml#L26

TreeBuilder has its own independent cycle detection logic: https://github.com/facebookexperimental/object-introspection/blob/c4194a9fbc92f7ed0f14aec2d81e26b8f0c411fb/src/TreeBuilder.cpp#L370-L377

### PR DESCRIPTION
**Pull request by JakeHillion**
## Summary

Moves all of the pointer detection logic out of TreeBuilder and into the data segment. Closes #104 as there is now no opportunity for OIL to have a different issue in pointer detection logic to OID. This makes it easier to type the datasegment as part of #95. There is room for improvement as null pointer implies the following will be a zero, meaning we could save a byte, but this is easier to implement for an MVP of the typed data segment.

Also fixes a bug in the `integration.py` tests where the config wasn't passed to OID, causing it to use the default. This took a lot of head scratching to debug.

## Test plan

- `make test-devel`
- CI
- Tried adding a test for `folly::IOBufQueue`. Unfortunately it's completely broken, because of #123 and not including the logic for traversing the `folly::IOBuf`, at minimum.

### CODE REVIEW

File: src/TreeBuilder.cpp [hunk 1]
```diff
@@ -215,8 +214,9 @@ void TreeBuilder::build(const std::vector<uint64_t>& data,
     auto& rootID = rootIDs.emplace_back(nextNodeID++);
 
     try {
-      // The first value is the address of the root object
-      pointers.insert(next());
+      // The first value is the address of the root object. Drop it as we don't
+      // need to manage pointer deduplication anymore.
+      next();
```
Comment (ajor) [inline src/TreeBuilder.cpp:219]: Can we just stop storing this pointer in the first place?

File: src/TreeBuilder.cpp [hunk 2]
```diff
@@ -741,7 +731,7 @@ void TreeBuilder::processContainer(const Variable& variable, Node& node) {
         // Contents aren't actually stored inline in this case,
         // but we set this to `true` so that we don't double-count
         // this string's data if we have seen it before.
-        contentsStoredInline = !shouldProcess(*node.pointer);
+        contentsStoredInline = (*node.pointer != 0);
```
Comment (ajor) [inline src/TreeBuilder.cpp:734]: How does this work? Won't node.pointer always be set?

**Review by ajor — COMMENTED** [review]
I think it might make the code clearer about what it's doing if we wrap the `next() == 0` checks away in a function with a descriptive name, e.g. `bool shouldFollowPointer() { return next() == 1; }`

File: src/TreeBuilder.cpp (hunk 2 above)
Comment (JakeHillion) [reply src/TreeBuilder.cpp]: It's completely wrong - my bad! It also fixes that test I skipped once this is done properly.

File: src/TreeBuilder.cpp (hunk 1 above)
Comment (JakeHillion) [reply src/TreeBuilder.cpp]: Yes. I was a little worried as I'm not sure I've got every entrypoint where it's written, but I put it in a separate commit so it can be easily reverted.

**Comment by JakeHillion** [comment]
> I think it might make the code clearer about what it's doing if we wrap the `next() == 0` checks away in a function with a descriptive name, e.g. `bool shouldFollowPointer() { return next() == 1; }`

I went for `if (bool followPointer = next() == 1; !followPointer)` as I think it solves the clarity issue without obfuscating the `next()` call (imo that makes it much harder to debug desyncs). In new treebuilder it'll be a `Sum` anyway which should clear things up.

File: src/TreeBuilder.cpp [hunk 3]
```diff
@@ -626,15 +616,15 @@ void TreeBuilder::processContainer(const Variable& variable, Node& node) {
       node.pointer = next();
       containerStats.length = *node.pointer ? 1 : 0;
       containerStats.capacity = 1;
-      if (!shouldProcess(*node.pointer)) {
+      if (bool followPointer = next() == 1; !followPointer) {
```
Comment (ttreyer) [inline src/TreeBuilder.cpp:619]: I have a hard time _following_ this line... The negation makes it confusing to understand at a glance.
Using some constants could help in this case. What about something like:
```cpp

/* Tag indicating if the pointer has  been followed or skipped */
enum class TrackPointerTag: uintptr_t {
  /* The content has been skipped.
   * It prevents double counting the footprint of a node the JIT code has seen before,
   * double counting content being stored inline, or getting stuck in an infinite loop
   * when processing circular linked list.
   */
  skipped = 0,
  followed = 1,
};

if (next() == TrackPointerTag::skipped) return;
```
